name: Build smartmontoolsQNAP
on:
  workflow_dispatch:  # Manual trigger only

jobs:
  build-windows:
    runs-on: windows-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
    - uses: actions/checkout@v4
    - name: Install MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: git mingw-w64-x86_64-gcc mingw-w64-x86_64-make mingw-w64-x86_64-autotools
    - name: Configure and Get Version
      shell: msys2 {0}
      id: get_version
      run: |
        cd smartmontools
        ./autogen.sh
        autoupdate
        ./configure --host=x86_64-w64-mingw32 CFLAGS="-O2 -static" CXXFLAGS="-O2 -static" LDFLAGS="-s"
        grep 'PACKAGE_VERSION' config.h | cut -d'"' -f2 > version.txt
        if grep -q '^smartmontools_release_date=' configure.ac; then
          echo "version=$(cat version.txt)q" >> $GITHUB_OUTPUT
        else
          echo "version=pre-$(cat version.txt)q" >> $GITHUB_OUTPUT
        fi
    - name: Build 64-bit
      shell: msys2 {0}
      run: |
        cd smartmontools
        make
        strip smartctl.exe smartd.exe
        mkdir -p bin
        mv smartctl.exe bin/smartctl.exe
        mv smartd.exe bin/smartd.exe
    - name: Build 32-bit
      shell: msys2 {0}
      run: |
        cd smartmontools
        make clean
        ./configure --host=i686-w64-mingw32 CFLAGS="-O2 -static" CXXFLAGS="-O2 -static" LDFLAGS="-s"
        make
        strip smartctl.exe smartd.exe
        mkdir -p bin32
        mv smartctl.exe bin32/smartctl.exe
        mv smartd.exe bin32/smartd.exe
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-binaries
        path: |
          smartmontools/bin/
          smartmontools/bin32/

  build-linux:
    runs-on: ubuntu-latest
    # No 'needs' to keep concurrent with build-windows
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential autoconf automake
    - name: Build
      run: |
        cd smartmontools
        ./autogen.sh
        autoupdate
        ./configure CFLAGS="-O2 -static" CXXFLAGS="-O2 -static" LDFLAGS="-s"
        make
        strip smartctl smartd
        mkdir -p bin
        mv smartctl bin/smartctl
        mv smartd bin/smartd
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: linux-binary
        path: smartmontools/bin/

  create-release:
    needs: [build-windows, build-linux]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
    - name: Create Zips
      run: |
        mkdir release
        # Win64
        cp -r artifacts/windows-binaries/bin release/smartmontoolsQNAP-${{ needs.build-windows.outputs.version }}-qnaptr-win64
        cd release
        zip -r smartmontoolsQNAP-${{ needs.build-windows.outputs.version }}-qnaptr-win64.zip smartmontoolsQNAP-${{ needs.build-windows.outputs.version }}-qnaptr-win64
        cd ..
        # Win32
        cp -r artifacts/windows-binaries/bin32 release/smartmontoolsQNAP-${{ needs.build-windows.outputs.version }}-qnaptr-win32
        cd release
        zip -r smartmontoolsQNAP-${{ needs.build-windows.outputs.version }}-qnaptr-win32.zip smartmontoolsQNAP-${{ needs.build-windows.outputs.version }}-qnaptr-win32
        cd ..
        # Linux
        cp -r artifacts/linux-binary/bin/ release/smartmontoolsQNAP-${{ needs.build-windows.outputs.version }}-qnaptr-linux-x64
        cd release
        zip -r smartmontoolsQNAP-${{ needs.build-windows.outputs.version }}-qnaptr-linux-x64.zip smartmontoolsQNAP-${{ needs.build-windows.outputs.version }}-qnaptr-linux-x64
        cd ..
        # Windows Combined
        mkdir -p release/smartmontoolsQNAP-${{ needs.build-windows.outputs.version }}-Windows/bin
        mkdir -p release/smartmontoolsQNAP-${{ needs.build-windows.outputs.version }}-Windows/bin32
        cp -r artifacts/windows-binaries/bin/* release/smartmontoolsQNAP-${{ needs.build-windows.outputs.version }}-Windows/bin/
        cp -r artifacts/windows-binaries/bin32/* release/smartmontoolsQNAP-${{ needs.build-windows.outputs.version }}-Windows/bin32/
        cd release
        zip -r smartmontoolsQNAP-${{ needs.build-windows.outputs.version }}-Windows.zip smartmontoolsQNAP-${{ needs.build-windows.outputs.version }}-Windows
        cd ..
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ needs.build-windows.outputs.version }}-qnaptr-${{ github.sha }}
        name: smartmontools ${{ needs.build-windows.outputs.version }} with QNAP TR-004 Support
        body: |
          Binaries for smartmontools ${{ needs.build-windows.outputs.version }} with QNAP TR-004 (`qnaptr`) support.
          - Windows 64-bit: `smartmontoolsQNAP-${{ needs.build-windows.outputs.version }}-qnaptr-win64.zip` (bin/smartctl.exe, bin/smartd.exe)
          - Windows 32-bit: `smartmontoolsQNAP-${{ needs.build-windows.outputs.version }}-qnaptr-win32.zip` (bin32/smartctl.exe, bin32/smartd.exe)
          - Linux 64-bit: `smartmontoolsQNAP-${{ needs.build-windows.outputs.version }}-qnaptr-linux-x64.zip` (bin/smartctl, bin/smartd)
          - Windows Combined: `smartmontoolsQNAP-${{ needs.build-windows.outputs.version }}-Windows.zip` (bin/smartctl.exe, bin32/smartctl.exe, etc.)
        files: |
          release/smartmontoolsQNAP-${{ needs.build-windows.outputs.version }}-qnaptr-win64.zip
          release/smartmontoolsQNAP-${{ needs.build-windows.outputs.version }}-qnaptr-win32.zip
          release/smartmontoolsQNAP-${{ needs.build-windows.outputs.version }}-qnaptr-linux-x64.zip
          release/smartmontoolsQNAP-${{ needs.build-windows.outputs.version }}-Windows.zip
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
