name: Build smartmontoolsQNAP
on:
  workflow_dispatch:  # Manual trigger only

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: git mingw-w64-x86_64-gcc mingw-w64-x86_64-make mingw-w64-x86_64-autotools
    - name: Build 64-bit
      shell: msys2 {0}
      run: |
        cd smartmontools
        ./autogen.sh
        autoupdate
        ./configure --host=x86_64-w64-mingw32 CFLAGS="-O2 -static" CXXFLAGS="-O2 -static" LDFLAGS="-s"
        make
        strip smartctl.exe smartd.exe
        mkdir -p bin
        mv smartctl.exe bin/smartctl.exe
        mv smartd.exe bin/smartd.exe
    - name: Build 32-bit
      shell: msys2 {0}
      run: |
        cd smartmontools
        make clean
        ./configure --host=i686-w64-mingw32 CFLAGS="-O2 -static" CXXFLAGS="-O2 -static" LDFLAGS="-s"
        make
        strip smartctl.exe smartd.exe
        mkdir -p bin32
        mv smartctl.exe bin32/smartctl.exe
        mv smartd.exe bin32/smartd.exe
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-binaries
        path: |
          smartmontools/bin/
          smartmontools/bin32/

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential autoconf automake
    - name: Build
      run: |
        cd smartmontools
        ./autogen.sh
        autoupdate
        ./configure CFLAGS="-O2 -static" CXXFLAGS="-O2 -static" LDFLAGS="-s"
        make
        strip smartctl smartd
        mkdir -p bin
        mv smartctl bin/smartctl
        mv smartd bin/smartd
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: linux-binary
        path: smartmontools/bin/

  create-release:
    needs: [build-windows, build-linux]
    runs-on: windows-latest  # Switch to Windows to run smartctl.exe
    steps:
    - uses: actions/checkout@v4
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
    - name: Get Version
      id: get_version
      shell: cmd  # Use CMD for Windows compatibility
      run: |
        artifacts\windows-binaries\bin\smartctl.exe --version > version.txt
        for /f "tokens=2" %%i in ('findstr "smartctl pre-" version.txt') do set "VERSION=%%i"
        echo VERSION=%VERSION% >> %GITHUB_ENV%
    - name: Create Zips
      shell: cmd  # Use CMD for Windows zip command
      run: |
        mkdir release
        :: Win64
        xcopy artifacts\windows-binaries\bin release\smartmontoolsQNAP-%VERSION%-qnaptr-win64\bin\ /E /I /Y
        cd release
        powershell -Command "Compress-Archive -Path smartmontoolsQNAP-%VERSION%-qnaptr-win64 -DestinationPath smartmontoolsQNAP-%VERSION%-qnaptr-win64.zip"
        cd ..
        :: Win32
        xcopy artifacts\windows-binaries\bin32 release\smartmontoolsQNAP-%VERSION%-qnaptr-win32\bin32\ /E /I /Y
        cd release
        powershell -Command "Compress-Archive -Path smartmontoolsQNAP-%VERSION%-qnaptr-win32 -DestinationPath smartmontoolsQNAP-%VERSION%-qnaptr-win32.zip"
        cd ..
        :: Linux
        xcopy artifacts\linux-binary\bin release\smartmontoolsQNAP-%VERSION%-qnaptr-linux-x64\bin\ /E /I /Y
        cd release
        powershell -Command "Compress-Archive -Path smartmontoolsQNAP-%VERSION%-qnaptr-linux-x64 -DestinationPath smartmontoolsQNAP-%VERSION%-qnaptr-linux-x64.zip"
        cd ..
        :: Windows Combined
        mkdir release\smartmontoolsQNAP-%VERSION%-Windows\bin
        mkdir release\smartmontoolsQNAP-%VERSION%-Windows\bin32
        xcopy artifacts\windows-binaries\bin release\smartmontoolsQNAP-%VERSION%-Windows\bin\ /E /I /Y
        xcopy artifacts\windows-binaries\bin32 release\smartmontoolsQNAP-%VERSION%-Windows\bin32\ /E /I /Y
        cd release
        powershell -Command "Compress-Archive -Path smartmontoolsQNAP-%VERSION%-Windows -DestinationPath smartmontoolsQNAP-%VERSION%-Windows.zip"
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ env.VERSION }}-qnaptr-${{ github.sha }}
        name: smartmontools ${{ env.VERSION }} with QNAP TR-004 Support
        body: |
          Binaries for smartmontools ${{ env.VERSION }} with QNAP TR-004 (`qnaptr`) support.
          - Windows 64-bit: `smartmontoolsQNAP-${{ env.VERSION }}-qnaptr-win64.zip` (bin/smartctl.exe, bin/smartd.exe)
          - Windows 32-bit: `smartmontoolsQNAP-${{ env.VERSION }}-qnaptr-win32.zip` (bin32/smartctl.exe, bin32/smartd.exe)
          - Linux 64-bit: `smartmontoolsQNAP-${{ env.VERSION }}-qnaptr-linux-x64.zip` (bin/smartctl, bin/smartd)
          - Windows Combined: `smartmontoolsQNAP-${{ env.VERSION }}-Windows.zip` (bin/smartctl.exe, bin32/smartctl.exe, etc.)
        files: |
          release/smartmontoolsQNAP-${{ env.VERSION }}-qnaptr-win64.zip
          release/smartmontoolsQNAP-${{ env.VERSION }}-qnaptr-win32.zip
          release/smartmontoolsQNAP-${{ env.VERSION }}-qnaptr-linux-x64.zip
          release/smartmontoolsQNAP-${{ env.VERSION }}-Windows.zip
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
