name: Build smartmontoolsQNAP
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:  # Manual trigger

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: git mingw-w64-x86_64-gcc mingw-w64-x86_64-make mingw-w64-x86_64-autotools
    - name: Build 64-bit
      shell: msys2 {0}
      run: |
        cd smartmontools
        ./autogen.sh
        autoupdate
        ./configure --host=x86_64-w64-mingw32 CFLAGS="-O2 -static" CXXFLAGS="-O2 -static" LDFLAGS="-s"
        make
        strip smartctl.exe
        mv smartctl.exe smartctl-x64.exe
    - name: Build 32-bit
      shell: msys2 {0}
      run: |
        cd smartmontools
        make clean
        ./configure --host=i686-w64-mingw32 CFLAGS="-O2 -static" CXXFLAGS="-O2 -static" LDFLAGS="-s"
        make
        strip smartctl.exe
        mv smartctl.exe smartctl-x32.exe
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: windows-binaries
        path: |
          smartmontools/smartctl-x64.exe
          smartmontools/smartctl-x32.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential autoconf automake
    - name: Build
      run: |
        cd smartmontools
        ./autogen.sh
        autoupdate
        ./configure CFLAGS="-O2 -static" CXXFLAGS="-O2 -static" LDFLAGS="-s"
        make
        strip smartctl
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: linux-binary
        path: smartmontools/smartctl

  create-release:
    needs: [build-windows, build-linux]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v3
    - name: Download Artifacts
      uses: actions/download-artifact@v3
      with:
        path: artifacts
    - name: Create Zip
      run: |
        mkdir release
        cp artifacts/windows-binaries/smartctl-x64.exe release/smartctl-7.4-qnaptr-win64.exe
        cp artifacts/windows-binaries/smartctl-x32.exe release/smartctl-7.4-qnaptr-win32.exe
        cp artifacts/linux-binary/smartctl release/smartctl-7.4-qnaptr-linux-x64
        cd release
        zip -r smartmontools-7.4-qnaptr-binaries.zip .
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v7.4-qnaptr-${{ github.sha }}
        name: smartmontools 7.4 with QNAP TR-004 Support
        body: |
          Binaries for smartmontools 7.4 with QNAP TR-004 (`qnaptr`) support.
          - Windows 64-bit: `smartctl-7.4-qnaptr-win64.exe`
          - Windows 32-bit: `smartctl-7.4-qnaptr-win32.exe`
          - Linux 64-bit: `smartctl-7.4-qnaptr-linux-x64`
        files: |
          release/smartctl-7.4-qnaptr-win64.exe
          release/smartctl-7.4-qnaptr-win32.exe
          release/smartctl-7.4-qnaptr-linux-x64
          release/smartmontools-7.4-qnaptr-binaries.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
